### ISSUE TITLE
Build is succeed but no HTML file attachment

### ISSUE THREAD

**Issue by jigneshc** [xximjasonxx/publish-html-task-extension#1]
Hi xximjasonxx,

I tried this extension, however the build is getting succeeded but there is no HTML file attached. I think it should be displayed beside the summary tab.

Thanks

**Comment by xximjasonxx** [comment]
Hi Jig,

The simple explanation is, the file is getting attached but the Release pipeline does not yet support showing it
https://developercommunity.visualstudio.com/content/problem/825871/vsotaskaddattachment-typedistributedtaskcoresummar-1.html

I will go ahead and do so and will update this ticket after confirming this in the next release of the platform

**Comment by jigneshc** [comment]
Hi xximjasonxx,

Thanks for the quick update.

I have implemented this task in build pipeline (Azure Devops Server 2017) and I think it supports adding new tab beside Summary tab. Let me know your thoughts on this.

Thanks

**Comment by xximjasonxx** [comment]
Jig,

The way I understand things is, this used to work on Release side and then it "broke" and thus there is a pending release. I believe if this task is used on the Build side you will get the new tab, though I have not tested it.

My main use for this is publishing an Artillery.io load report - so I am awaiting the next release by Microsoft to see if this does or does not do what I need it to.

I will gladly accept a PR if you have some thoughts on what might be missing. :)

Jason

**Comment by xximjasonxx** [comment]
Update on this - the fix has been deployed to Azure DevOps however, the extension does not appear to be working for one reason or another. I am currently investigating

**Comment by xximjasonxx** [comment]
This is now working, though the attachment looks weird so I need to investigate that. Closing this for now though
