### ISSUE TITLE
Does not work. 

### ISSUE THREAD

**Issue by stoopered** [xximjasonxx/publish-html-task-extension#2]
When I publish the html, it shows the html code instead of the page.

![Screen Shot 2020-02-05 at 9 48 02 AM](https://user-images.githubusercontent.com/14861898/73857525-ae4f8880-47fc-11ea-8cc8-e19bef26356a.png)

Should be 
![Screen Shot 2020-02-05 at 9 49 36 AM](https://user-images.githubusercontent.com/14861898/73857683-e2c34480-47fc-11ea-8dc0-85f91039cae2.png)

**Comment by xximjasonxx** [comment]
I will take a look at this as soon as I can. Thanks for letting me know

**Comment by xximjasonxx** [comment]
One thing I did notice while looking through this, apart from the HTML not rendering, your source does have local references (styles.css for example) - this will break once the rendering process is fixed since the task only publishes the HTML and not the backing resources.

**Comment by stoopered** [comment]
Thanks for the quick response. I removed the stylesheet reference, and it still does not work.

I was looking at the Microsofts example of build results enhancer, and when I replace their html with my doc, it does display, I do have to include their scripts section at the top of my html. The problem with theirs is that I am unable to select my own file at build time, and I do not know enough about building these tasks yet to make it usable.

I could send you my HTML if you think that would help. I am using the free Aqua to scan my docker and generate the html.

https://github.com/microsoft/vsts-extension-samples/tree/master/build-results-enhancer

**Comment by xximjasonxx** [comment]
I did confirm with some other HTML that this is not working. I will try to find time over the weekend to look at what broke. Apologies that I cannot look at it any sooner

**Comment by stoopered** [comment]
No problem, thanks for your help!

**Comment by xximjasonxx** [comment]
I pushed an updated version (v1.2.2) this evening. My testing shows it is rendering HTML and images in both build and release cases. However, only in Build will it add a new tab, in Release it appends itself to the release instance.

Tip: In both cases, look at stripping the non viewable portion of the HTML (that is the head section mainly, you also do not need the body tag).  Hope this works for you now. Cheers

**Comment by stoopered** [comment]
Thanks I will check it out!
