### ISSUE TITLE
README or usage missing

### ISSUE THREAD

**Issue by daniyalj** [xximjasonxx/publish-html-task-extension#3]
Is there any documentation on how to use this extension? I am looking to do something similar to #2 with Aqua scan html reports

**Comment by xximjasonxx** [comment]
Greetings,

Absolutely, I got hung up with other things and forgot to add a README to this. Given I am basically at home for the foreseeable future, I will add this to my list

**Comment by xximjasonxx** [comment]
Well I published the README but my screen shots didnt come through, here they are for postarity
![Selection_001](https://user-images.githubusercontent.com/287220/77855967-151c6d00-71c2-11ea-8951-9cc91255e098.png)
![Selection_002](https://user-images.githubusercontent.com/287220/77855968-177ec700-71c2-11ea-8671-27d3a80e7584.png)
