### ISSUE TITLE
HTML file not load properly!

### ISSUE THREAD

**Issue by rick-jordan** [xximjasonxx/publish-html-task-extension#4]
Hi @xximjasonxx,

I need your help. I am trying yo use your extension to publish an html file which include the results from UFT (it's a program that I used to automate tests) but after configuring and running the build I get only this:

![image](https://user-images.githubusercontent.com/62395332/77538763-28fd6180-6e98-11ea-8576-44e775eb2280.png)

Can you help me? Here is the file that I want to load (I need to put in a zip file, because this form does not support html file types):
[run_results.zip](https://github.com/xximjasonxx/publish-html-task-extension/files/4381002/run_results.zip)

I would appreciate your help and time on this issue. 
Best Regards,
Diogo Cruz

**Comment by xximjasonxx** [comment]
I can try to look at it this weekend

Jason

**Comment by rick-jordan** [comment]
Hi @xximjasonxx 

Thank you very much for your help.
I'll wait until you give me your opinion/analysis on this. 

Regards,
Diogo

**Comment by xximjasonxx** [comment]
Diego,

I had a look at the contents of the file and it is rather complex, far more complex than I think would be supportable within VSO, especially given the real estate. Could you maybe publish these outputs to Azure Blob storage and use the Website hosting feature? That way you could produce a simple HTML output file with high level details (pass/fail percentage) and a person could follow the link to the full output in storage?

That would be the only thought that I would have. Other than, I think your case would require a far more sophisticated integration to be supported within the pipeline itself.

Sorry I could not be more help

Jason

Sorry

**Comment by rick-jordan** [comment]
Hi Jason,
Thanks for your reply and support. 
Azure Blob storage is new for me ... I never used it ... but I will try to look into it further ahead ... 
Does this functionality is available within pipelines? My idea as you already understood is to run a pipeline (in my specific case, a couple of tests with UFT and then present the report to the user as easiest as possible .. )

However there is not an extension just to open directly an html file without any issue ....

Many thanks once again ...
Diogo

**Comment by xximjasonxx** [comment]
Diogo,

Certainly simple HTML can be exported with a great amount of ease but, in
general you would want to avoid JavaScript for this sort of thing. Given
that what your sent me, its effectively a full fledged application that
lets you drill into the results, its not something that this extension is
going to support. My suggestion was aimed at getting you to a simple HTML
file this extension would support with a link to this more full featured
export that you presented.

Thanks
