### ISSUE TITLE
Update readme to support .yml

### ISSUE THREAD

**Issue by L0wry** [xximjasonxx/publish-html-task-extension#6]
Hi @xximjasonxx how do I consume this library if using .yml

**Comment by xximjasonxx** [comment]
Your best bet would be to open your pipeline in the Visaul Studio online
editor. There is a sidebar along the right that features all of the
available tasks. Find that and it will give you a GUI interface based on
the available inputs. Once you click add it will drop the YAML into your
pipeline for you. Great way to experiment I have found

**Comment by L0wry** [comment]
Awesome, thanks for that! 
@xximjasonxx
