### ISSUE TITLE
Error - task execution handler was not found

### ISSUE THREAD

**Issue by Maxim-Krivobokov** [xximjasonxx/publish-html-task-extension#7]
Hello. I,m using this extension with TFS 2018, agent version 2.136.1 (64bit). Agent OS is Windows Server2012 R2 64 bit.
The extension was downloaded from official marketplace. 

Every time I'm getting this error message: 
```
##[error]A supported task execution handler was not found. The task does not carry an implementation that is compatible with your current operating system 'Windows'. Contact the task author for more details.
```
Please, tell me what can be the reason.

**Comment by xximjasonxx** [comment]
It sounds like you are using TFS on-premise and not the build agents in the Cloud, is that correct?

**Comment by Maxim-Krivobokov** [comment]
Yes, that's correct.

**Comment by xximjasonxx** [comment]
To be honest, I have never tested this extension in an environment that uses TFS on-premise. I would need to research to see what the differences are. If they are minor I can look for time to make them and create a new version.

**Comment by Weqqen** [comment]
+1 Also on prem.
To be specific I was hoping to show Gatling reports (they are static html+js+css) within the build report. But got the same error. as Maxim.

**Comment by xximjasonxx** [comment]
I will state for the record that such an addition is not something I will be adding in the near term. I am fine if someone wants to take the existing solution and fix the problem. I do not run TFS on-prem
